# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{papyrus}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alexey Artamonov"]
  s.date = %q{2011-06-27}
  s.description = %q{Library helps to organize search through your documents, filtering by tags and authors. Library based on sphinx search.}
  s.email = %q{i@useruby.com}
  s.executables = ["papyrus"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/papyrus",
    "lib/papyrus.rb",
    "lib/papyrus/crc32.rb",
    "lib/papyrus/document.rb",
    "lib/papyrus/document/export.rb",
    "lib/papyrus/document/metadata.rb",
    "lib/papyrus/folder.rb",
    "lib/papyrus/folder/export.rb",
    "lib/papyrus/folder/index.rb",
    "lib/papyrus/folder/sphinx.rb",
    "lib/papyrus/settings.rb",
    "lib/papyrus/sphinx/config.rb",
    "papyrus.gemspec",
    "spec/papyrus/document_spec.rb",
    "spec/papyrus/folder_spec.rb",
    "spec/papyrus/settings_spec.rb",
    "spec/papyrus/sphinx/config_spec.rb",
    "spec/papyrus_spec.rb",
    "spec/samples/conf/papyrus.conf",
    "spec/samples/documents/test/01.html.haml",
    "spec/samples/documents/test/02.html.haml",
    "spec/spec_helper.rb",
    "spec/support/papyrus_conf.rb",
    "spec/support/start_papyrus.rb",
    "tasks/distribution.rb",
    "tasks/testing.rb"
  ]
  s.homepage = %q{http://github.com/useruby/papyrus}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.7.2}
  s.summary = %q{Library for organizing your static documents}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<haml>, [">= 0"])
      s.add_runtime_dependency(%q<riddle>, [">= 0"])
      s.add_runtime_dependency(%q<slop>, [">= 0"])
      s.add_runtime_dependency(%q<settingslogic>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.1"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<require_relative>, [">= 0"])
      s.add_development_dependency(%q<ruby-debug>, [">= 0"])
    else
      s.add_dependency(%q<haml>, [">= 0"])
      s.add_dependency(%q<riddle>, [">= 0"])
      s.add_dependency(%q<slop>, [">= 0"])
      s.add_dependency(%q<settingslogic>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.1"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<require_relative>, [">= 0"])
      s.add_dependency(%q<ruby-debug>, [">= 0"])
    end
  else
    s.add_dependency(%q<haml>, [">= 0"])
    s.add_dependency(%q<riddle>, [">= 0"])
    s.add_dependency(%q<slop>, [">= 0"])
    s.add_dependency(%q<settingslogic>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.1"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<require_relative>, [">= 0"])
    s.add_dependency(%q<ruby-debug>, [">= 0"])
  end
end

